version: '3'
services:
   redis:
      image: redis:alpine
      container_name: redis-master

   django_service:
       image: celery_project:v2
       container_name: django_container
       ports:
         - 8000:8000
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
         - celeryuser:/django
       depends_on:
         - db
   db:
     image: postgres
     ports:
       - 5432:5432
     volumes:
       - pgdata:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     container_name: postgres_db

   celery:
     restart: always
     container_name: celery
     image: celery_project:v2
     command: celery -A MyCeleryProject.celery worker --pool=solo -l debug
     volumes:
       - celeryservice:/django
     depends_on:
       - db
       - redis
       - django_service

   celerybeat:
     restart: always
     container_name: celery_beat
     image: celery_project:v2
     command: celery -A MyCeleryProject beat -l INFO
     volumes:
       - beat_service:/django
     depends_on:
       - db
       - redis
       - django_service


volumes:
  celeryuser:
  pgdata:
  celeryservice:
  beat_service: